version: 2
updates:
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directories:
    - "/"
    - "/conformance"
    - "/tests"
    - "/tools"
    schedule:
      interval: "weekly"
    groups:
      k8s.io: # Group k8s.io golang dependencies updates
          patterns:
            - "k8s.io/*"
            - "sigs.k8s.io/*"
    labels:
      - go
      - dependencies
      - ok-to-test
      - release-note-none

  # Dependencies listed in conformance/echo-basic/go.mod
  - package-ecosystem: "gomod"
    directory: "/conformance/echo-basic/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      k8s.io: # Group k8s.io golang dependencies updates
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
    labels:
      - go
      - dependencies
      - ok-to-test
      - release-note-none

  # Dependencies listed in Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - docker
      - dependencies
      - ok-to-test
      - release-note-none

  # Dependencies listed in requirements.txt
  - package-ecosystem: "pip"
    directory: "/hack/mkdocs/image"
    schedule:
      interval: "weekly"
    groups:
      mkdocs-deps:
        patterns:
          - "*"
    labels:
      - python
      - dependencies
      - ok-to-test
      - release-note-none
  
  #  Github actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "release-note-none"
      - "ok-to-test"

