processor:
  ignoreTypes:
    - "(Elasticsearch|Kibana|ApmServer)List$"
    - "ParseError$"
    - "List$"
    - "ReferencePolicy$"
  ignoreFields:
    - "TypeMeta$"

render:
  kubernetesVersion: 1.22
  knownTypes:
    - name: SecretObjectReference
      package: sigs.k8s.io/gateway-api/apis/v1beta1
      link: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.SecretObjectReference
