name: CRD Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  crd-validation:
    name: CEL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Available versions at https://raw.githubusercontent.com/kubernetes-sigs/controller-tools/HEAD/envtest-releases.yaml
        k8s_version: [v1.34.0, v1.33.0, v1.32.0, v1.31.0, v1.30.3]
        crd_channel: [standard, experimental]
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # tag=v6.0.1
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # tag=v6.1.0
      - name: Run CRD Validation tests
        env:
          K8S_VERSION: ${{ matrix.k8s_version }}
          CRD_CHANNEL: ${{ matrix.crd_channel }}
        run: |
          make CEL_TEST_K8S_VERSION="${K8S_VERSION}" CEL_TEST_CRD_CHANNEL="${CRD_CHANNEL}" test.crds-validation
