name: CRD Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  crd-validation:
    name: CEL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Available versions at https://raw.githubusercontent.com/kubernetes-sigs/controller-tools/HEAD/envtest-releases.yaml
        # Our goal is to cover the most recent 5 minor versions, even if the oldest one is EOL.
        k8s_version: [v1.35.0, v1.34.1, v1.33.0, v1.32.0, v1.31.0]
        crd_channel: [standard, experimental]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # tag=v6.3.0
        with:
          go-version-file: 'go.work'
      - name: Run CRD Validation tests
        env:
          K8S_VERSION: ${{ matrix.k8s_version }}
          CRD_CHANNEL: ${{ matrix.crd_channel }}
        run: |
          make CEL_TEST_K8S_VERSION="${K8S_VERSION}" CEL_TEST_CRD_CHANNEL="${CRD_CHANNEL}" test.crds-validation
